### PR TITLE
Improve artist/song matching

### PR DESCRIPTION
**Pull request by AmirJaballah**
Migrating from youtube music playlist to Spotify, I have encountered too much Error and song not found during the process.
By leveraging on the unique video Id to find the original channel (artist name) this improved significantly the matching.

### CODE REVIEW

**Comment by ghost** [comment]
I ran your code but its giving key errors. I tried it on multiple playlists, all ended up giving key error.
```
Traceback (most recent call last):
  File "c:\Users\ctrla\Desktop\youtubetospotify\main.py", line 27, in <module>
    main()
  File "c:\Users\ctrla\Desktop\youtubetospotify\main.py", line 11, in main
    songs = yt.get_songs_from_playlist(yt_playlist_id)
  File "c:\Users\ctrla\Desktop\youtubetospotify\youtube.py", line 72, in get_songs_from_playlist
    result = self.__fetch_songs(youtube, playlist_id)
  File "c:\Users\ctrla\Desktop\youtubetospotify\youtube.py", line 52, in __fetch_songs
    videoId = item['contentDetails']['videoId']
KeyError: 'contentDetails'
PS C:\Users\ctrla\Desktop\youtubetospotify>
```
Can you test this and maybe share the playlist id you used.
Thanks.

**Comment by ghost** [comment]
The playlist id that I used is:
`Playlist id : PLgzTt0k8mXzEpH7-dOCHqRZOsakqXmzmG`

**Comment by AmirJaballah** [comment]
we need to retrieve the `contentDetails` when requesting the `playListItems` pls check last commit.

**Comment by ghost** [comment]
At first when I ran it, it added only 6 songs out of 149. I noticed that artist's names were repeated twice hence low number of songs being added. I fixed artist name and noticed it added 142/149 songs and 478/906  for 2 playlists different playlists. The old program managed to get the exact same number and runs faster too. I don's see any improvement in the number of songs being added unless, you tried it on a different playlists where it performed better. Please run more tests and provide some examples.

**Pull request closed without merging**
